# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
logging:
    level:
      ROOT: INFO
      com.sappenin: INFO
      org.springframework: INFO
spring:
  output:
    ansi:
      enabled: ALWAYS
  http:
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      max-file-size: 2KB
      max-request-size: 2KB
  # Database Settings
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

ilpv4:
  connector:
    # ILP address of the connector. This property can be omitted if an account with relation=parent
    # is configured under accounts.
    ilp_address: test.sappenin
    secret: secret

###
#   H2 Settings
###
h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false