# See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
logging:
  level:
    ROOT: INFO
    com.sappenin: INFO
    org.springframework: INFO
    org.springframework.web.socket: DEBUG
server:
  port: 8080
spring:
  output:
    ansi:
      enabled: ALWAYS
  http:
    # MULTIPART (MultipartProperties)
    multipart:
      enabled: false
      max-file-size: 2KB
      max-request-size: 2KB
  # Database Settings
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

ilpv4:
  connector:
    secret: shhhhhh
    # ILP address of the connector. This property can be omitted if an account with relation=parent
    # is configured under accounts.
    ilp_address: test.example

    #########
    # Peers
    #########
    accounts:
    # MicroPayments only...
    # TODO: rateLimit, throughput, routes, options.
    #See https://github.com/interledgerjs/ilp-connector/blob/f938cbe1f156e3330a611daf0f8874b8b9fb35e4/src/schemas/Config.json
    - interledger_address: test.parent.micro.usd
      description: Parent micro-payments Account (USD)
      relationship: PARENT
      # Name of the ILP plugin that should be used for this account.
      pluginType: "MOCK"

    - interledger_address: test.parent.unlimited.usd
      description: Unlimited Parent Account (USD)
      relationship: PARENT
      assetCode: USD
      pluginType: "MOCK"
      assetScale: 9

###
#   H2 Settings
###
h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false