# dummy secrets and keys that make it easy to run for dev purposes but are completely insecure for running a real-world
# connector because the passwords and keys would be known
interledger:
  connector:
    open-payments:
      issuer: "http://localhost:8080"
      authorizationIssuer: "http://localhost:8000"
      authorizationEndpoint: "http://localhost:8000/authorize"
      tokenEndpoint: "http://localhost:8000/token"
      invoicesEndpoint: "http://localhost:8000/invoices"
      mandatesEndpoint: "http://localhost:8000/mandates"
      assetsSupported:
        - assetCode: "USD"
          assetScale: 2
        - assetCode: "XRP"
          assetScale: 9
    ## ILP address of the connector.
    nodeIlpAddress: test1.connie
    enabledFeatures:
      require32ByteSharedSecrets: false
    globalPrefix: test
    adminPassword: password
    keystore:
      primary: jks
      jks:
        enabled: true
        filename: crypto/crypto.p12
        password: password
        secret0_alias: secret0
        secret0_password: password
