spring:
  output:
    ansi:
      enabled: ALWAYS
  http:
    multipart:
      enabled: false
      max-file-size: 32KB
      max-request-size: 32KB
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#  redis:
#    host: localhost
#    port: 6379
interledger:
  connector:
    adminPassword: password
    keystore:
      jks:
        enabled: true
        filename: crypto/crypto.p12
        password: password
        secret0_alias: secret0
        secret0_password: password
    enabledProtocols:
      blastEnabled: true
      pingProtocolEnabled: true
      peerConfigEnabled: true
      peerRoutingEnabled: true
#    nodeIlpAddress: test.xpring-dev.java1
    defaultJwtTokenIssuer: https://java1.xpring.dev/
    globalRoutingSettings:
      # Represents the plaintext value of `shh`, encrypted.
      routingSecret: enc:JKS:crypto.p12:secret0:1:aes_gcm:AAAADKZPmASojt1iayb2bPy4D-Toq7TGLTN95HzCQAeJtz0=
#      # how to include routes
#      staticRoutes:
#        - targetPrefix: test.xpring-dev.java2
#          peerAccountId: bob

logging:
  level:
    ROOT: INFO
    com.sappenin: INFO
    org.interledger: INFO
    org.springframework: INFO
    org.springframework.security: INFO
server:
  port: 8080
  http2:
    enabled: true
  jetty:
    max-http-post-size: 32767
